// lib/db.ts
import { Product } from "@/types/product";

/**
 * Product database with sample leather goods
 * In production, this would be replaced with a real database
 */
export const products: Product[] = [
    // New Arrivals
    {
        id: "1",
        name: "Heritage Leather Boots",
        detail: "Handcrafted full-grain leather boots with Goodyear welt construction. Premium quality leather that ages beautifully over time.",
        imageUrl: "/products/boot-1.jpg",
        category: "boots",
        price: 389,
        inStock: true,
        sizes: ["40", "41", "42", "43", "44"],
        isNew: true,
        isBestSeller: false,
    },
    {
        id: "2",
        name: "Weekender Travel Bag",
        detail: "Full-grain leather carry essentials. Spacious main compartment with interior pockets for organization.",
        imageUrl: "/products/bag-1.jpg",
        category: "bags",
        price: 529,
        inStock: true,
        isNew: true,
        isBestSeller: false,
    },
    {
        id: "3",
        name: "Leather Bomber Jacket",
        detail: "Classic silhouette meets modern comfort. Lined with soft viscose for all-day wearability.",
        imageUrl: "/products/jacket-1.jpg",
        category: "coats",
        price: 899,
        inStock: true,
        sizes: ["S", "M", "L", "XL"],
        isNew: true,
        isBestSeller: true,
    },
    {
        id: "4",
        name: "Minimalist Card Holder",
        detail: "Slim profile, 4 card slots, and a center compartment. Perfect for minimalist everyday carry.",
        imageUrl: "/products/accessory-1.jpg",
        category: "accessories",
        price: 89,
        inStock: true,
        isNew: true,
        isBestSeller: true,
    },
    // Best Sellers
    {
        id: "5",
        name: "Field Messenger Bag",
        detail: "Versatile crossbody bag with adjustable strap. Perfect for work or weekend adventures.",
        imageUrl: "/products/bag-2.jpg",
        category: "bags",
        price: 449,
        inStock: true,
        isNew: false,
        isBestSeller: true,
    },
    {
        id: "6",
        name: "Chelsea Boots",
        detail: "Elastic side panels and pull tab. Elegant and timeless design for any occasion.",
        imageUrl: "/products/boot-2.jpg",
        category: "boots",
        price: 359,
        inStock: true,
        sizes: ["40", "41", "42", "43"],
        isNew: false,
        isBestSeller: true,
    },
    {
        id: "7",
        name: "Leather Backpack",
        detail: "Modern silhouette with vintage leather finish. Waxed canvas interior lining.",
        imageUrl: "/products/bag-3.jpg",
        category: "bags",
        price: 479,
        inStock: true,
        isNew: false,
        isBestSeller: true,
    },
    {
        id: "8",
        name: "Leather Gloves",
        detail: "Lined with cashmere for ultimate warmth. Touchscreen compatible fingertips.",
        imageUrl: "/products/accessory-2.jpg",
        category: "accessories",
        price: 129,
        inStock: true,
        sizes: ["S", "M", "L"],
        isNew: false,
        isBestSeller: true,
    },
    {
        id: "9",
        name: "Motorcycle Jacket",
        detail: "Asymmetric zip with quilted shoulders. Classic biker style with modern details.",
        imageUrl: "/products/jacket-2.jpg",
        category: "coats",
        price: 749,
        inStock: true,
        sizes: ["S", "M", "L", "XL"],
        isNew: false,
        isBestSeller: true,
    },
    {
        id: "10",
        name: "Leather Belt",
        detail: "Full-grain leather with brass buckle. Hand-stitched edges for durability.",
        imageUrl: "/products/accessory-3.jpg",
        category: "accessories",
        price: 79,
        inStock: true,
        sizes: ["30", "32", "34", "36", "38"],
        isNew: false,
        isBestSeller: false,
    },
];